apiVersion: v1
kind: ConfigMap
metadata:
  name: clasificacion-sentimiento-config
data:
  MODEL_NAME: "distilbert-base-uncased-finetuned-sst-2-english"
  LOG_LEVEL: "INFO"
  MAX_SENTENCE_LENGTH: "512"
---
apiVersion: v1
kind: Secret
metadata:
  name: clasificacion-sentimiento-secret
type: Opaque
data:
  API_KEY: <base64_encoded_api_key>