apiVersion: apps/v1
kind: Deployment
metadata:
  name: clasificacion-sentimiento-deployment
  labels:
    app: clasificacion-sentimiento
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clasificacion-sentimiento
  template:
    metadata:
      labels:
        app: clasificacion-sentimiento
    spec:
      containers:
      - name: clasificacion-sentimiento
        image: clasificacion-sentimiento:latest
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TRANSFORMERS_CACHE
          value: "/tmp/transformers_cache"
        resources:
          limits:
            cpu: "1000m"
            memory: "1.5Gi"
          requests:
            cpu: "250m"
            memory: "768Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3