apiVersion: v1
kind: Service
metadata:
  name: clasificacion-sentimiento-loadbalancer
  labels:
    app: clasificacion-sentimiento
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: clasificacion-sentimiento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  sessionAffinity: None