apiVersion: v1
kind: Service
metadata:
  name: clasificacion-sentimiento-service
  labels:
    app: clasificacion-sentimiento
spec:
  selector:
    app: clasificacion-sentimiento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP