apiVersion: v1
kind: Service
metadata:
  name: microserv-llm-service
  labels:
    app: microserv-llm
spec:
  selector:
    app: microserv-llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP